In [1]:
import qrcode
from faker import Faker
from faker_vehicle import VehicleProvider
import pandas as pd
from faker.providers import automotive
import random
import streamlit as st
import web3 as Web3
import pandas as pd
import path as Path
import sqlalchemy as db
from sqlalchemy import create_engine, MetaData, Table

In [2]:
engine = create_engine('sqlite:///database_file.db')
connection = engine.connect()

In [3]:
pd.read_sql_table("Texas License Plates", con=engine)

,index,First Name,Last Name,Social Security,License Plate,VIN Number,License Plate Status,Address 1,City,Postal Code,State,Country,Year,Make,Model,Category
0,0,Corey,Webb,220-69-3767,RNP 640,7JAID36TFVM191606,Pending,260 Wilson Landing,Port Janicemouth,79350,Texas,United States,2010,Toyota,Highlander,SUV
1,1,Michelle,Hendricks,586-56-5060,WAE 607,7YCYG73WVTF509653,Permanent,597 Victoria Villages,East George,76394,Texas,United States,2016,Hyundai,Tucson Fuel Cell,SUV
2,2,Harold,Griffith,297-22-6980,THA 742,8FAYQ91BKRA587472,Not in Database,1786 Anderson Unions Apt. 995,South Alexandria,77859,Texas,United States,2001,Audi,S4,"Wagon, Sedan"
3,3,James,Lee,523-81-1618,DNB 853,1XNFX59BUZC399801,Pending,4402 Dwayne Square,Nathanshire,77867,Texas,United States,1994,Plymouth,Sundance,Hatchback
4,4,Tina,Foster,259-12-8318,JQN 937,1ALOM88BGOL465271,Pending,410 Reynolds Road Apt. 480,Lake Thomas,78786,Texas,United States,2016,Chevrolet,Sonic,"Sedan, Hatchback"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,Annette,Guzman,451-77-8451,OHO 192,3DWPQ86RLII394865,Not in Database,224 Griffin Ports,New Thomas,77338,Texas,United States,1997,Buick,Regal,Sedan
99996,99996,Courtney,Acevedo,077-76-5592,RCV 986,3SPKU78GOVY732629,Pending,347 Hale Gateway,Zimmermanside,76046,Texas,United States,2003,Mitsubishi,Eclipse,"Coupe, Convertible"
99997,99997,Maria,Miller,093-74-3499,LYN 689,3DRCV29LEDF000953,Pending,4590 Murillo Shoals Suite 703,Bethberg,79496,Texas,United States,2008,Toyota,Highlander,SUV
99998,99998,Christian,Berg,140-69-4643,XDO 475,0MWMK69TRAM937671,Temporary,037 Chambers Knoll,Taylormouth,78554,Texas,United States,2019,Jeep,Wrangler Unlimited,SUV
99999,99999,Elizabeth,Harris,260-73-6577,EEZ 914,4ULEH51VPJY512951,Pending,63386 Todd Ranch,Stuartstad,79052,Texas,United States,2003,Ford,E350 Super Duty Cargo,Van/Minivan