In [22]:
from web3 import Web3
import pandas as pd
import os
import json
from dotenv import load_dotenv
import sqlalchemy as sql
from pathlib import Path


from mnemonic import Mnemonic
from bip44 import Wallet
from web3 import Account
load_dotenv()
w3 = Web3(Web3.HTTPProvider(os.getenv("WEB3_PROVIDER_URI")))

In [23]:
connection_string = "sqlite:///database_file.db"

In [24]:
engine = sql.create_engine(connection_string)

In [25]:
engine.table_names()

/var/folders/bk/z2_y916x5gx26_4vt2c_99zh0000gn/T/ipykernel_35127/4162273999.py:1: SADeprecationWarning: The Engine.table_names() method is deprecated and will be removed in a future release.  Please refer to Inspector.get_table_names(). (deprecated since: 1.4)
  engine.table_names()

['Texas License Plates']

In [26]:
df = pd.read_sql("Texas License Plates",con=engine)

In [27]:
df

,index,First Name,Last Name,Social Security,License Plate,VIN Number,License Plate Status,Address 1,City,Postal Code,State,Country,Year,Make,Model,Category
0,0,Dan,Davenport,461-97-2773,DJG 154,3KVLS58NSLC361691,Not in Database,775 William Points Suite 051,East Jessica,79541,Texas,United States,1998,Mitsubishi,Montero,SUV
1,1,Beth,Williamson,644-07-6647,UDN 513,2TIJE70HFGE505470,Temporary,6864 Schroeder Tunnel Apt. 675,East Bonnie,77175,Texas,United States,2013,Ford,F150 Super Cab,Pickup
2,2,Peggy,Clark,161-78-8795,FLR 034,7PCJB83RPIU068713,Temporary,209 Martin Stravenue Apt. 680,Brianmouth,77082,Texas,United States,2014,BMW,X6,SUV
3,3,Jason,Wang,145-90-7173,IYB 988,4NHON88SKZJ519635,Temporary,06031 Duke Turnpike,Port Shannonside,78759,Texas,United States,2015,Volvo,V60,Wagon
4,4,Stephanie,Rivera,258-20-9406,WZB 033,8LNEO63ZLLQ836113,Not in Database,4293 Shawn Via,Glennfort,79927,Texas,United States,2018,Chevrolet,Colorado Crew Cab,Pickup
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,Debra,Nguyen,368-75-6545,UDQ 730,4CJPT03KUMW796628,Temporary,00941 Tyler Trafficway,Jonfurt,78268,Texas,United States,2014,Mercedes-Benz,S-Class,Sedan
99996,99996,Adam,Walls,813-14-8519,QUB 100,8TDKC97WALS229936,Permanent,5990 Bell Shore Apt. 611,Lake Jeff,76317,Texas,United States,2018,Chevrolet,Suburban 3500HD,SUV
99997,99997,John,Doyle,541-18-7859,QNN 906,4QCNN24JIIC180572,Permanent,8461 Crystal Mall Apt. 436,Jamesburgh,75738,Texas,United States,2004,Chevrolet,Silverado 2500 HD Regular Cab,Pickup
99998,99998,Kristina,Anthony,670-06-3450,LZH 779,6XLYN69ZLVG809100,Temporary,46935 Christopher Well Suite 212,Carrmouth,78602,Texas,United States,1999,Ford,F250 Super Duty Crew Cab,Pickup
99999,99999,Jason,Black,017-82-4670,YBH 968,6XBCX11MUFX654505,Not in Database,14312 Solomon Extension Suite 480,Leefort,78277,Texas,United States,2018,Subaru,WRX,Sedan

In [28]:
def load_contract():

    # Load the contract ABI
    with open(Path('Eli/abi.json')) as f:
        artwork_abi = json.load(f)

    contract_address = os.getenv("SMART_CONTRACT_ADDRESS")

    # Load the contract
    contract = w3.eth.contract(
        address=contract_address,
        abi=artwork_abi
    )

    return contract

In [30]:
contract = load_contract()

In [33]:
address = "0xd848F0e8D832cfb0969a1982fd647f60a0b3d944"

In [31]:
contract.all_functions.(
    address,
    "Elias"
)

[<Function approve(address,uint256)>,
 <Function balanceOf(address)>,
 <Function baseURI()>,
 <Function getApproved(uint256)>,
 <Function isApprovedForAll(address,address)>,
 <Function name()>,
 <Function ownerOf(uint256)>,
 <Function safeTransferFrom(address,address,uint256)>,
 <Function safeTransferFrom(address,address,uint256,bytes)>,
 <Function setApprovalForAll(address,bool)>,
 <Function supportsInterface(bytes4)>,
 <Function symbol()>,
 <Function tokenByIndex(uint256)>,
 <Function tokenOfOwnerByIndex(address,uint256)>,
 <Function tokenURI(uint256)>,
 <Function totalSupply()>,
 <Function transferFrom(address,address,uint256)>]

In [ ]:
contract.functions.reg